version: '3.8'

services:
  web:
    build: .
    env_file:
      - ./weather/.env
    expose:
      - "8000"
    entrypoint: "sh ./docker-entrypoint.sh"
    volumes:
      - static_volume:/home/app/web/staticfiles
    restart: "always"
    depends_on:
      forecast-db:
        condition: service_healthy

  forecast-db:
    image: postgres:16-bullseye
    container_name: postgres-db
    env_file:
      - db/.env
    expose:
      - "5432"
    ports:
      - "5433:5432"
    restart: "always"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx:1.24-bullseye
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./nginx/data:/data:ro
      - static_volume:/home/app/web/staticfiles:ro
    ports:
      - "80:80"
    restart: 'always'
    depends_on:
      web:
        condition: service_started


volumes:
  postgres_data:
  static_volume:
